# Generated by Django 3.1.7 on 2021-03-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catagory',
            options={'verbose_name_plural': 'Catagories'},
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='john doe', max_length=50),
        ),
    ]
